In [12]:
import random

maleFirstName = []
femaleFirstName = []
lastName = []

malename = open('male-first-names.txt', 'r')
maleFirstName = malename.read().splitlines()

femalename = open('female-first-name.txt' , 'r')
femaleFirstName = femalename.read().splitlines()

surname = open('last-names.txt', 'r')
lastName = surname.read().splitlines()

ranMaleName = random.choice(maleFirstName)
ranFemaleName = random.choice(femaleFirstName)
ranLastName = random.choice(lastName)

maleCandidate = f"{ranMaleName} {ranLastName}"
femaleCandidate = f"{ranFemaleName} {ranLastName}"

gender = random.choice(['male' , 'female'])
if gender == 'male':
    firstName = (maleFirstName)
else:
    firstName = (femaleFirstName)
    
year1 = 2019
year2 = 2023

year = random.randint(year1,year2)

grade = {"A":5, "B":4, "C":3, "D":2, "E":1, "F":0}

wgp = []


wgp = []
totalc = []

def calculateGpa():
    creditUnit = []
    totalcu = 0
    
    for i in range(len(courses)):
        randomGrade = random.choice(list(grade.keys()))
        score = int(grade[randomGrade])
        
        credit = random.randint(1, 3)
        creditUnit.append(credit)
        
        gradepoint = score * credit
        wgp.append(gradepoint)
    
    totalwgp = sum(wgp)
    totalcu = sum(creditUnit)
    totalc.append(totalcu)
    return (totalwgp / totalcu)
    
print('NAME: ', maleCandidate)
print("\n")
print("GENDER: ", gender.capitalize())
print("\n")
print("YEAR: " , year)
print("\n")
print("========  =====  ============\nCOURSE    GRADE   CREDIT UNIT\n========  =====  =============")

dg = []
credit_units = []
for courses in ["MAT112", "CPE123", "GST104", "MAT221", "CPI109", "CPT342", "EET124", "AET214"]:
    randomGrade = random.choice(list(grade.keys()))
    dg.append(randomGrade)
    creditUnit = random.randint(1, 3)
    credit_units.append(creditUnit)
    print(f"{courses}      {randomGrade}              {creditUnit}")
print("========  =====  ============")

    
print("")
creditLoad = sum(credit_units)
print(f"TOTAL CREDIT LOAD: {creditLoad}\n")
gpaResult = calculateGpa()
print(f"GPA: {gpaResult:.2f}")
print("\n")

if(gpaResult >= 4.5):
    print("REMARK: EXCELLENT")
elif(gpaResult >= 3.5 and gpaResult < 4.5):
    print("REMARK: GOOD")
elif(gpaResult >= 2.5 and gpaResult < 3.5):
    print("REMARK: FAIR")
elif(gpaResult >= 1.5 and gpaResult < 2.5):
    print("REMARK: POOR")
else:
    print("REMARK: FAIL")



NAME:  ALEXIS LIVI


GENDER:  Female


YEAR:  2020


========  =====  ============
COURSE    GRADE   CREDIT UNIT
========  =====  =============
MAT112      C              3
CPE123      A              3
GST104      D              3
MAT221      F              3
CPI109      C              2
CPT342      E              3
EET124      D              2
AET214      D              1
========  =====  ============

TOTAL CREDIT LOAD: 20

GPA: 3.80


REMARK: GOOD


In [7]:
import numpy as np
arr = np.array([[1,2,3,4,5],[2,3,3,4,5]])
print(arr)
print(type(arr))
print(arr.ndim)

[[1 2 3 4 5]
 [2 3 3 4 5]]
<class 'numpy.ndarray'>
2


In [8]:
import numpy as np

arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('number of dimensions :', arr.ndim)

[[[[[1 2 3 4]]]]]
number of dimensions : 5


In [14]:
import numpy as np
num = np.array([[1,2,3,4,1,2,3,6,7] , [3,4,5,1,2,3,4]])
print(num[1,4])

<ipython-input-14-9bf9f8a4108e>:2: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  num = np.array([[1,2,3,4,1,2,3,6,7],[3,4,5,1,2,3,4]])


IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed

In [25]:
import numpy as np
numbers = np.array([1.5,2.6,3.7,4.9,5])
newarr = numbers.astype('int')
print(newarr)

[1 2 3 4 5]
